[package]
name = "mindustry_launcher"
version = "0.1.0"
authors = ["Shift <shiftkeydeveloper@gmail.com>"]
edition = "2018"

[dependencies]
iced = "0.1.1"
serde = "1.0.116"
serde_json = "1.0.57"
serde_derive = "1.0.116"
